| Name                   | Website                            | ICObench profile                                        | Country                | Raised amout                  | Website backup (from web.archive.org)                             | ICObench backup (from web.archive.org)                                                      |
|------------------------|------------------------------------|---------------------------------------------------------|------------------------|-------------------------------|-------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| AidCoin                | https://www.aidcoin.co/            | https://icobench.com/ico/aidcoin                        | Switzerland            | $15,854,305                   | https://web.archive.org/web/*/https://www.aidcoin.co/             | https://web.archive.org/web/20181203130605/https://icobench.com/ico/aidcoin                 |
| ArtCoin                | https://www.artcoinfund.com/       | N/A                                                     |                        |                               |                                                                   | N/A                                                                                         |
| BitMiner               | https://www.bitminerfactory.io/en/ | https://icobench.com/ico/bitminer-factory               | Bosnia and Herzegovina | N/A                           |                                                                   | https://web.archive.org/web/20181203130822/https://icobench.com/ico/bitminer-factory        |
| BitSong                | https://bitsong.io/                | https://icobench.com/ico/bitsong                        | Malta                  | N/A                           | https://web.archive.org/web/*/https://bitsong.io/                 | https://web.archive.org/web/20181203134010/https://icobench.com/ico/bitsong                 |
| BrikBit                | https://brikbit.io/                | https://icobench.com/ico/brikbit                        | Switzerland            | N/A                           |                                                                   |                                                                                             |
| Coincrowd              | https://coincrowd.me               | https://icobench.com/ico/coincrowd                      | Italy                  | Not disclosed (ICO completed) | https://web.archive.org/web/*/https://coincrowd.me                | https://web.archive.org/web/20181203131136/https://icobench.com/ico/coincrowd               |
| CryptoForecast         | https://www.cryptoforecast.com     | https://icobench.com/ico/cryptoforecast                 | Italy                  | $193,984                      | https://web.archive.org/web/*/https://www.cryptoforecast.com      | https://web.archive.org/web/20181203131339/https://icobench.com/ico/cryptoforecast          |
| Cryptogram             | https://cryptogram4u.com/          | N/A                                                     | Malta                  | N/A                           |                                                                   | N/A                                                                                         |
| CryptoPie              | https://www.cryptopie.io/          | N/A                                                     | Gran Canaria (Spain)   | N/A                           |                                                                   | N/A                                                                                         |
| DeFund Project         | https://www.defundproject.net/     | https://icobench.com/ico/defund-project                 | Italy                  | Not disclosed (ICO completed) | N/A                                                               | https://web.archive.org/web/20181203131804/https://icobench.com/ico/defund-project          |
| Eidoo                  | https://eidoo.io/                  | https://icobench.com/ico/eidoo                          | Switzerland            | $28,000,000                   | https://web.archive.org/web/*/https://eidoo.io/                   | https://web.archive.org/web/20181203131911/https://icobench.com/ico/eidoo                   |
| Epocum                 | https://www.epocum.com             | https://icobench.com/ico/epocum                         | Italy                  | $50,000                       | https://web.archive.org/web/*/https://www.epocum.com              | https://web.archive.org/web/20181203132035/https://icobench.com/ico/epocum                  |
| EquaCoin               | http://equacoin.com/               | N/A                                                     | Not disclosed          | Not disclosed (ICO completed) | https://web.archive.org/web/*/http://equacoin.com/                | N/A                                                                                         |
| Fidelity House         |                                    | https://icobench.com/ico/fidelity-house                 | Switzerland            | N/A                           |                                                                   |                                                                                             |
| Fractal Token          | https://fto.ninja                  | https://icobench.com/ico/fractal-token-crowdsale        | Italy                  | Not disclosed (ICO completed) | https://web.archive.org/web/*/https://fto.ninja                   | https://web.archive.org/web/20181203132144/https://icobench.com/ico/fractal-token-crowdsale |
| FriendsFinger          | https://www.friendsfingers.com/    | https://icobench.com/ico/friendsfingers                 | Italy                  | N/A                           | https://web.archive.org/web/*/https://www.friendsfingers.com/     |                                                                                             |
| Friendz                | https://friendz.io/                | https://icobench.com/ico/friendz                        | Switzerland            | $27,525,000                   | https://web.archive.org/web/*/https://friendz.io/                 |                                                                                             |
| GastroAdvisor          | https://www.gastroadvisor.com/     | https://icobench.com/ico/gastro-advisor                 | Switzerland            | N/A                           |                                                                   |                                                                                             |
| GooRuf                 | https://www.gooruf.io/             | https://icobench.com/ico/gooruf                         | Hong Kong              |                               |                                                                   |                                                                                             |
| ICOStart               | https://icostart.ch/               | https://icobench.com/ico/icostart                       | Switzerland            | $200,000                      |                                                                   |                                                                                             |
| Innovative Bioresearch |                                    | https://icobench.com/ico/innovative-bioresearch         |                        |                               |                                                                   |                                                                                             |
| InsCoin                | https://inscoin.co/                | https://icobench.com/ico/inscoin-for-knox-project       | Estonia                | Not disclosed (ICO completed) | https://web.archive.org/web/20180609061922/https://inscoin.co/    |                                                                                             |
| Jointly                | https://www.jpcompany.solutions/   | https://icobench.com/ico/jointly                        | Italy                  | Not disclosed (ICO completed) |                                                                   |                                                                                             |
| Kapu                   |                                    | https://icobench.com/ico/kapu                           |                        |                               |                                                                   |                                                                                             |
| Kheper                 |                                    | https://icobench.com/ico/kheper                         |                        |                               |                                                                   |                                                                                             |
| Kleos                  |                                    | https://icobench.com/ico/kleos                          |                        |                               |                                                                   |                                                                                             |
| Local World Forwarders |                                    | https://icobench.com/ico/local-world-forwarders         |                        |                               |                                                                   |                                                                                             |
| Look Lateral           |                                    | https://icobench.com/ico/look-lateral                   |                        |                               |                                                                   |                                                                                             |
| Luxochain              | https://luxochain.io/              |                                                         |                        | Not disclosed (ICO completed) |                                                                   |                                                                                             |
| MakeItViral            |                                    | https://icobench.com/ico/makeitviral                    |                        |                               |                                                                   |                                                                                             |
| Mama Mutua             |                                    | https://icobench.com/ico/mamamutua                      |                        |                               |                                                                   |                                                                                             |
| Masternode Invest      | https://masternodeinvest.io/       | https://icobench.com/ico/masternode-invest              | Switzerland            | N/A                           |                                                                   |                                                                                             |
| Multiversum            |                                    | https://icobench.com/ico/multiversum                    |                        |                               |                                                                   |                                                                                             |
| MyMazzu                | http://ico.mymazzu.com/            | https://icobench.com/ico/mymazzu                        | Malta                  | N/A                           | https://web.archive.org/web/*/http://ico.mymazzu.com/             | https://web.archive.org/web/20181203133808/https://icobench.com/ico/mymazzu                 |
| Namacoin               | https://namacoin.io/               | https://icobench.com/ico/namacoin                       | Lithuania              |                               | https://web.archive.org/web/20181201191357/https://namacoin.io/   |                                                                                             |
| ORS                    | https://www.orsgroup.io/           | https://icobench.com/ico/ors-ico                        |                        |                               |                                                                   |                                                                                             |
| Parkingo               |                                    |                                                         |                        |                               |                                                                   |                                                                                             |
| Phi Token              | https://www.phitoken.io/           | https://icobench.com/ico/phi-token                      |                        |                               |                                                                   |                                                                                             |
| Pigzbe                 |                                    | https://icobench.com/ico/pigzbe                         |                        |                               |                                                                   |                                                                                             |
| Plutus                 |                                    | https://icobench.com/ico/plutus                         |                        |                               |                                                                   |                                                                                             |
| Prosume Energy         |                                    | https://icobench.com/ico/prosume-energy                 |                        |                               |                                                                   |                                                                                             |
| RipaEx                 |                                    | https://icobench.com/ico/ripaex                         |                        |                               |                                                                   |                                                                                             |
| SgamePro               | https://sgamepro.io                | https://icobench.com/ico/sgamepro                       |                        |                               |                                                                   |                                                                                             |
| Sidera                 | https://sidera.io/                 | https://icobench.com/ico/sidera-blockchain-technologies |                        |                               | https://web.archive.org/web/20180725033752/https://www.sidera.io/ |                                                                                             |
| SingularityNet         |                                    | https://icobench.com/ico/singularitynet                 |                        |                               |                                                                   |                                                                                             |
| Skillchain             |                                    | https://icobench.com/ico/skillchain                     |                        |                               |                                                                   |                                                                                             |
| SUPERIUM               |                                    | https://icobench.com/ico/superium                       |                        |                               |                                                                   |                                                                                             |
| Tatatu                 |                                    | https://icobench.com/ico/tatatu                         |                        |                               |                                                                   |                                                                                             |
| Thrive                 |                                    | https://icobench.com/ico/thrive                         |                        |                               |                                                                   |                                                                                             |
| Togacoin               |                                    |                                                         |                        |                               |                                                                   |                                                                                             |
| Tokedo                 |                                    | https://icobench.com/ico/tokedo                         |                        |                               |                                                                   |                                                                                             |
| Ubiatar                |                                    | https://icobench.com/ico/ubiatarplay-io                 |                        |                               |                                                                   |                                                                                             |
| Vank                   | https://vank.net/                  |                                                         |                        |                               |                                                                   |                                                                                             |
| Xriba                  |                                    | https://icobench.com/ico/xriba                          |                        |                               |                                                                   |                                                                                             |
| Yookye                 |                                    | https://icobench.com/ico/yookye                         |                        |                               |                                                                   |                                                                                             |
| Zupply                 |                                    | https://icobench.com/ico/zupply                         |                        |                               |                                                                   |                                                                                             |
| Followine              | https://followine.io/en/           |                                                         |                        |                               |                                                                   |                                                                                             |
